services:
  dev-terminal:
    build: .
    hostname: dev-terminal
    ports:
      - "7681:7681"
      - "2222:22"
    restart: unless-stopped
    container_name: dev-terminal
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./persistence.img:/persistence.img
