services:
  dev-terminal:
    build: .
    hostname: dev-terminal
    ports:
      - "7681:7681"
      - "2222:22"
    restart: unless-stopped
    container_name: dev-terminal
    privileged: true
    environment:
      - TZ=${TZ}
      - WEB_USER=${WEB_USER}
      - WEB_PASS=${WEB_PASS}
      - ENCRYPTION_PASS=${ENCRYPTION_PASS}
    ports:
      - "7681:7681"
      - "2222:2222"
    volumes:
      - ./persistence.img:/persistence.img
